name: Github Actions
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
      accessKey:
        description: LT Access Key
        required: true
      sampleRepoLink:
        description: Link to the HyperExecute sample repo
        default: https://github.com/john190501/RD_Single_Device_Types
        required: true

jobs:
  HyperExecute-Selenium:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        id: rd-single-device-types
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone ${{ github.event.inputs.sampleRepoLink }}
          echo "STEP 2) Download CLI and setting environment variables"
          cd Job_Prioritization
          curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
          export LT_USERNAME=${{ github.event.inputs.username }}
          export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
          echo $LT_USERNAME
          echo $LT_ACCESS_KEY
          ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config RD-Single-Device-Type.yaml --download-artifacts --download-report
